## Importing Libraries

In [1]:
import numpy as np
from tensorflow.keras.optimizers import Adam
from keras.utils import np_utils
from keras.layers import Activation, Dropout, Convolution2D, GlobalAveragePooling2D
from keras.models import Sequential
import tensorflow as tf
import tensorflow.keras.applications.mobilenet
import os

In [5]:
IMG_SAVE_PATH = r'C:\Users\hp\testing_data_final\train'

In [6]:
Str_to_Int = {
    'Neutral': 0,
    'Happy': 1,
    'Sad': 2,
    'Scared': 3,
    'Agony': 4
}

NUM_CLASSES = 5


def str_to_Int_mapper(val):
    return Str_to_Int[val]

## Model Architecture

In [7]:
def get_model():
    model = Sequential([
        tf.keras.applications.mobilenet.MobileNet(input_shape=(240, 240, 3), include_top=False),
        Dropout(0.5),
        Convolution2D(5, (1, 1), padding='valid'),
        Activation('relu'),        # Rectified Linear Unit - Activation Function
        GlobalAveragePooling2D(),  # Pooling Layer
        Activation('softmax')      # Softmax - Activation Function - For Multi Class Classification
    ])
    return model

In [9]:
import PIL

dataset = []
for directory in os.listdir(IMG_SAVE_PATH):
    path = os.path.join(IMG_SAVE_PATH, directory)
    for image in os.listdir(path):
        new_path = os.path.join(path, image)
        img = np.asarray(PIL.Image.open(new_path))
        dataset.append([img, directory]) 

In [10]:
dataset

[[array([[[226, 212, 212],
          [225, 211, 211],
          [224, 210, 210],
          ...,
          [236, 221, 218],
          [236, 221, 218],
          [236, 221, 218]],
  
         [[228, 214, 214],
          [227, 213, 213],
          [226, 212, 212],
          ...,
          [237, 222, 219],
          [238, 223, 220],
          [238, 223, 220]],
  
         [[229, 215, 215],
          [229, 215, 215],
          [228, 214, 214],
          ...,
          [237, 222, 219],
          [237, 222, 219],
          [237, 222, 219]],
  
         ...,
  
         [[ 78,  54,  52],
          [ 76,  52,  50],
          [ 70,  49,  46],
          ...,
          [ 77,  65,  75],
          [ 83,  71,  81],
          [ 88,  76,  86]],
  
         [[ 72,  51,  48],
          [ 70,  49,  46],
          [ 67,  46,  43],
          ...,
          [ 76,  64,  74],
          [ 82,  70,  80],
          [ 86,  74,  84]],
  
         [[ 67,  46,  43],
          [ 66,  45,  42],
          [ 65,  44,  41

In [11]:
data, labels = zip(*dataset)
temp = list(map(str_to_Int_mapper, labels))

In [12]:
temp[0]

4

In [13]:
# one hot encoding the labels
import keras
labels = keras.utils.to_categorical(temp)

# define the model
model = get_model()
model.compile(
    
    optimizer=Adam(lr=0.0001),         # lr = learning_rate
    loss='categorical_crossentropy',   # Multi-class classification
    metrics=['accuracy']  
)


D:\Sonu\MINE\Mmmm..Personal\Ana\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [33]:
print(np.array(data[0].shape))
print(np.array(labels.shape))

[240 240   3]
[21570     5]


## Model Summary

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 mobilenet_1.00_224 (Functio  (None, 7, 7, 1024)       3228864   
 nal)                                                            
                                                                 
 dropout (Dropout)           (None, 7, 7, 1024)        0         
                                                                 
 conv2d (Conv2D)             (None, 7, 7, 5)           5125      
                                                                 
 activation (Activation)     (None, 7, 7, 5)           0         
                                                                 
 global_average_pooling2d (G  (None, 5)                0         
 lobalAveragePooling2D)                                          
                                                                 
 activation_1 (Activation)   (None, 5)                 0

In [16]:
# start training
model.fit(np.array(data), np.array(labels))

675/675 [==============================] - 1907s 3s/step - loss: 0.0637 - accuracy: 0.9817


In [32]:
# define the model
model_new = get_model()
model_new.compile(
    optimizer=Adam(lr=0.0001),         # lr = learning_rate
    loss='categorical_crossentropy',   # Multi-class classification
    metrics=['accuracy']  
)

D:\Sonu\MINE\Mmmm..Personal\Ana\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [34]:
## EPOCHS + VALIDATION

model_new.fit(np.array(data), np.array(labels), epochs = 5, shuffle = True, validation_split = 0.1)

Epoch 1/5
607/607 [==============================] - 1848s 3s/step - loss: 0.0704 - accuracy: 0.9786 - val_loss: 0.6241 - val_accuracy: 0.8183
Epoch 2/5
607/607 [==============================] - 1921s 3s/step - loss: 6.8137e-04 - accuracy: 0.9999 - val_loss: 0.8527 - val_accuracy: 0.7793
Epoch 3/5
607/607 [==============================] - 1978s 3s/step - loss: 2.6184e-04 - accuracy: 1.0000 - val_loss: 0.6682 - val_accuracy: 0.8308
Epoch 4/5
607/607 [==============================] - 1903s 3s/step - loss: 0.0013 - accuracy: 0.9997 - val_loss: 0.8922 - val_accuracy: 0.7399
Epoch 5/5
607/607 [==============================] - 1890s 3s/step - loss: 0.0029 - accuracy: 0.9994 - val_loss: 0.5594 - val_accuracy: 0.8507


In [35]:
# save the model for later use
model.save("face_sentiment_mark3.h5")

In [17]:
# save the model for later use
model.save("face_sentiment_mark2_train_test.h5")

In [19]:
IMG_SAVE_PATH_TESTING = r'C:\Users\hp\testing_data_final\test'

In [20]:
import PIL
# import cv2
dataset_testing = []
for directory in os.listdir(IMG_SAVE_PATH_TESTING):
    path = os.path.join(IMG_SAVE_PATH_TESTING, directory)
    for image in os.listdir(path):
        new_path = os.path.join(path, image)
        img = np.asarray(PIL.Image.open(new_path))
#         img = cv2.imread(new_path)
#         img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
#         img = cv2.resize(img, (240, 240))
        dataset_testing.append([img, directory]) 

In [22]:
testing_data, testing_labels = zip(*dataset)
testing_temp = list(map(str_to_Int_mapper, testing_labels))

In [23]:
testing_labels = keras.utils.to_categorical(testing_temp)

In [29]:
model.evaluate(np.array(testing_data), np.array(testing_labels))

675/675 [==============================] - 426s 618ms/step - loss: 2.9884e-04 - accuracy: 1.0000


[0.0002988437772728503, 1.0]

In [25]:
testing_labels[4]

array([0., 0., 0., 0., 1.], dtype=float32)

In [26]:
labels[4]

array([0., 0., 0., 0., 1.], dtype=float32)

In [27]:
testing_data[0]

array([[[226, 212, 212],
        [225, 211, 211],
        [224, 210, 210],
        ...,
        [236, 221, 218],
        [236, 221, 218],
        [236, 221, 218]],

       [[228, 214, 214],
        [227, 213, 213],
        [226, 212, 212],
        ...,
        [237, 222, 219],
        [238, 223, 220],
        [238, 223, 220]],

       [[229, 215, 215],
        [229, 215, 215],
        [228, 214, 214],
        ...,
        [237, 222, 219],
        [237, 222, 219],
        [237, 222, 219]],

       ...,

       [[ 78,  54,  52],
        [ 76,  52,  50],
        [ 70,  49,  46],
        ...,
        [ 77,  65,  75],
        [ 83,  71,  81],
        [ 88,  76,  86]],

       [[ 72,  51,  48],
        [ 70,  49,  46],
        [ 67,  46,  43],
        ...,
        [ 76,  64,  74],
        [ 82,  70,  80],
        [ 86,  74,  84]],

       [[ 67,  46,  43],
        [ 66,  45,  42],
        [ 65,  44,  41],
        ...,
        [ 75,  63,  73],
        [ 80,  68,  78],
        [ 85,  73,  83]]

In [28]:
data[0]

array([[[226, 212, 212],
        [225, 211, 211],
        [224, 210, 210],
        ...,
        [236, 221, 218],
        [236, 221, 218],
        [236, 221, 218]],

       [[228, 214, 214],
        [227, 213, 213],
        [226, 212, 212],
        ...,
        [237, 222, 219],
        [238, 223, 220],
        [238, 223, 220]],

       [[229, 215, 215],
        [229, 215, 215],
        [228, 214, 214],
        ...,
        [237, 222, 219],
        [237, 222, 219],
        [237, 222, 219]],

       ...,

       [[ 78,  54,  52],
        [ 76,  52,  50],
        [ 70,  49,  46],
        ...,
        [ 77,  65,  75],
        [ 83,  71,  81],
        [ 88,  76,  86]],

       [[ 72,  51,  48],
        [ 70,  49,  46],
        [ 67,  46,  43],
        ...,
        [ 76,  64,  74],
        [ 82,  70,  80],
        [ 86,  74,  84]],

       [[ 67,  46,  43],
        [ 66,  45,  42],
        [ 65,  44,  41],
        ...,
        [ 75,  63,  73],
        [ 80,  68,  78],
        [ 85,  73,  83]]